#
# Executes commands at the start of an interactive session.
#
# Authors:
#   Sorin Ionescu <sorin.ionescu@gmail.com>
#

# Source Prezto.
if [[ -s "${ZDOTDIR:-$HOME}/.zprezto/init.zsh" ]]; then
  source "${ZDOTDIR:-$HOME}/.zprezto/init.zsh"
fi


## Customize to your needs...
#

path=(
  $HOME/.local/bin
  $HOME/.local/nvim-macos/bin
  $HOME/{,s}bin(N)
  $path
)

# if we have ghcup installed, add executables
if [[ -n "$GHCUP_INSTALL_BASE_PREFIX" ]]; then
  path=(
    /c/ghcup/bin
    "$APPDATA/local/bin"
    $path
  )
fi

# Ensure path arrays do not contain duplicates.
typeset -gU cdpath fpath mailpath path

# this is for WSL. TODO: can it be removed on newer systems?
if [ -f "/mnt/c/Program Files/OpenSSH/ssh-sk-helper.exe" ]; then
  export SSH_SK_HELPER="/mnt/c/Program Files/OpenSSH/ssh-sk-helper.exe"
fi

# use NeoVim by default
if [ -x "$(command -v nvim)" ]; then
  alias vim=nvim
fi

export EDITOR='vim'
export VISUAL='vim'

# read fzf zsh settings
[ -f ~/.fzf.zsh ] && source ~/.fzf.zsh
