#
# Executes commands at the start of an interactive session.
#
# Authors:
#   Sorin Ionescu <sorin.ionescu@gmail.com>
#

# Source Prezto.
if [[ -s "${ZDOTDIR:-$HOME}/.zprezto/init.zsh" ]]; then
  source "${ZDOTDIR:-$HOME}/.zprezto/init.zsh"
fi


## Customize to your needs...
#

# Lines configured by zsh-newuser-install
HISTFILE=~/.histfile
HISTSIZE=1000
SAVEHIST=1000
bindkey -v
setopt hist_ignore_all_dups
setopt hist_ignore_space
# End of lines configured by zsh-newuser-install


alias ls='ls --color=auto'

autoload -U compinit promptinit
compinit
promptinit

prompt walters

setopt completealiases

